name: image build and upload
on:
  workflow_dispatch:
    inputs:
      git_hash:
        description: git hash, tag or branch of svxlink repo to build for
        required: false
        default: master
      docker_tag:
        description: docker tag to generate the image with
        default: latest


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Fetch svxlink
        run: |
          git clone https://github.com/sm0svx/svxlink.git
          # we stay on master here, as older versions don't have an up to date ubuntu image in the builder, with arm64 support

      - name: Build builder image
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          tags: ghcr.io/hobbyscoop/svxlink-builder-image:latest
          context: svxlink/docker/ubuntu-build/
          platforms: linux/arm64
          file: svxlink/docker/ubuntu-build/Dockerfile
          cache-from: type=registry,ref=ghcr.io/hobbyscoop/svxlink-builder-image:buildcache
          cache-to: type=registry,ref=ghcr.io/hobbyscoop/svxlink-builder-image:buildcache,mode=max

      - name: Build svxlink
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          tags: ghcr.io/hobbyscoop/svxlink:${{ inputs.docker_tag }}
          build-args: |
             GIT_BRANCH=${{ inputs.git_hash }}
          context: .
          platforms: linux/arm64
          file: Dockerfile.build
          cache-from: type=registry,ref=ghcr.io/hobbyscoop/svxlink:buildcache-${{ inputs.docker_tag }}
          cache-to: type=registry,ref=ghcr.io/hobbyscoop/svxlink:buildcache-${{ inputs.docker_tag }},mode=max

