name: image build and upload
on:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Fetch svxlink
        run: |
          git clone https://github.com/sm0svx/svxlink.git
      - name: Build builder image
        run: |
          docker buildx build --platform linux/arm64 -f svxlink/docker/ubuntu-build/Dockerfile -t builder-image svxlink/docker/ubuntu-build/
          docker run -v $PWD:/build -w /build --platform linux/arm64 builder-image /home/svxlink/build-svxlink.sh
      - name: Build final image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/hobbyscoop/svxlink:latest .
